
# List the start up tasks. Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks
tasks:
  - name: utils
    before: |
      sudo apt-get install tree
  - name: Configure AWS_CLI
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    before: |
      cd /workspace
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install --bin-dir /usr/local/bin --install-dir /usr/local/aws-cli --update
      cd $THEIA_WORKSPACE_ROOT




# Learn more from ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstart
