#!/usr/bin/env bash

# Exit immediately if any command returns a non-zero status
set -e

echo "Bucket Created!"

# Check for bucket name
if [ -z "$1" ]; then
    echo "There needs to be a bucket name eg. ./bucket my-bucket-name"
    exit 1
fi

# Access the first argument (in this case) 
BUCKET_NAME=$1

# Use the input variable in a script
aws s3api create-bucket \
    --bucket $BUCKET_NAME \
    --region eu-west-2 \
    --create-bucket-configuration=LocationConstraint=eu-west-2 \
--query Location \
--output text






