#!/usr/bin/env bash
echo "Objecet Deleted!"

# Exit immediately if any command returns a non-zero status
set -e

# Check for bucket name
if [ -z "$1" ]; then
    echo "There needs to be a bucket name eg. ./bucket my-bucket-name"
    exit 1
fi

# Access the first argument (in this case) 
BUCKET_NAME=$1

# Use the input variable in a script

aws s3api list-objects-v2 \
    --bucket $BUCKET_NAME \
    --query 'Contents[].Key' \
    | jq -n '{Objects: [inputs | .[] | {Key: .}]}' > /tmp/delete_objects.json
    #--region eu-west-2 \
aws s3api delete-objects --bucket $BUCKET_NAME --delete file:///tmp/delete_objects.json

#--delete file:///tmp/delete_objects.json