#!/bin/env bash

echo "==sync"

# Exit immediately if any command returns a non-zero status
#set -e

# Check for AWS CLI installation
if ! command -v aws &> /dev/null; then
    echo "AWS CLI is not installed. Please install it first."
    exit 1
fi

# Check for bucket name
if [ -z "$1" ]; then
    echo "There needs to be a bucket name. Example: ./bucket my_bucket_name"
    exit 1
fi

BUCKET_NAME="$1"

# Check for filename prefix
if [ -z "$2" ]; then
    echo "There needs to be a filename prefix. Example: ./bucket my-bucket-name my_filename-prefix"
    exit 1
fi

FILENAME_PREFIX="$2"

# Check if the bucket exists, if not, create it
if ! aws s3api head-bucket --bucket "$BUCKET_NAME" 2>/dev/null; then
    echo "Creating S3 bucket: $BUCKET_NAME"
    aws s3api create-bucket \
    --bucket "$BUCKET_NAME" \
    --region eu-west-2 \
    --create-bucket-configuration=LocationConstraint=eu-west-2 \
    --query Location \
    --output text
fi

# Create a temporary directory to store random files
TEMP_DIR=$(mktemp -d)

# Remove folder if it already exists
rm -r "$TEMP_DIR"

# We will create a folder to store our output files
mkdir -p "$TEMP_DIR"

# Generate a random number to manage the number of files created
NUM_FILES=$((RANDOM % 6 + 5))

# Generate and upload random files
for ((i=1; i<=$NUM_FILES; i++)); do
    FILE_NAME="$TEMP_DIR/${FILENAME_PREFIX}_$i.txt"
    #FILE_PATH="$TEMP_DIR/$FILE_NAME"

    # Generate random content (in this example, 1 KB of random data)
    dd if=/dev/urandom of="$FILE_NAME" bs=1024 count=$((RANDOM % 1024 + 1)) 2>/dev/null 
done

tree "$TEMP_DIR"

aws s3 sync "$TEMP_DIR" "s3://$BUCKET_NAME/files"

# Clean up temporary directory
rm -r "$TEMP_DIR"
